name: DAISY Pipeline 2
collections:
  wiki:
    output: true
    permalink: /wiki/:path.html
defaults:
  - scope:
      path: ""
      type: wiki
    values:
      layout: wiki
markdown: kramdown
kramdown:
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    line_numbers: false
    css: class
baseurl: "/pipeline"
site_base: "http://daisy.github.io"
meta_file: meta.ttl
exclude:
  - /meta.ttl